authors:
  me:
    name: Scott Wilcox
    description: Creator
    avatar: https://avatars.githubusercontent.com/u/84348540?v=4
    url: https://twitter.com/intent/follow?screen_name=hereandtomorrow  